### ISSUE TITLE
Incompatibility with Sinytra Connector due to Forge Version Requirements

### ISSUE THREAD

**Issue by fin600** [yungnickyoung/YUNGs-Cave-Biomes#10]
Sinytra Connector requires forge version 47.1.3 on 1.20.1, Cave Biomes requires 47.1.47. Is there any way to lower the needed version further for support?

**Comment by yungnickyoung** [comment]
Not sure I understand, why are you not able to use 47.1.47? Does Sinytra Connector require specifically Forge 47.1.3, without support for newer versions?

**Comment by fin600** [comment]
Yes, Sinytra on 1.20.1 doesn't support newer Forge versions and won't change this due to focusing on newer Minecraft versions,

**Comment by yungnickyoung** [comment]
What happens if you try to use a newer version of Forge? I just booted up Sinytra Connector on Forge 47.3.0 and it seems to boot up okay

EDIT: well I do see that they explicitly mention using 47.1.3 on their CF page. I'll see if I can lower the required version for Cave Biomes
