### ISSUE TITLE
Enchanted Ice melts the ice around it, making ugly looking waterfalls

### ISSUE THREAD

**Issue by dabomb6405** [yungnickyoung/YUNGs-Cave-Biomes#11]
Because Enchanted Ice is a light source, it melts the ice around it, causing a bunch of waterfalls to be made.
Maybe Enchanted Ice could be a light source that doesn't melt snow and ice? That would fix the issue and give it a new use outside of ambience

Currently playing on Forge 1.20.1

**Comment by dabomb6405** [comment]
Okay, looking into it more, this seems to only happen when the enchanted ice columns generate on the edge or outside of the biome.

**Comment by yungnickyoung** [comment]
Yeah, this doesn't really seem like too much of an issue. The light value from the enchanted ice should be too low to cause ice blocks to melt. I agree having a light source that doesn't melt ice would be cool, but unfortunately with how MC's lighting system is set up it isn't easily doable.
